name:                planning-graph
version:             0.1.0.0
github:              "adam-kucz/planning-graph"
license:             BSD3
author:              "Adam Kucz"
maintainer:          "-"
copyright:           "2018 Adam Kucz"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/planning-graph#readme>

dependencies:
- base >= 4.7 && < 5
- containers == 0.5.*
- mtl == 2.2.*
- hspec == 2.4.*

library:
  source-dirs: src

executables:
  planning-graph-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - planning-graph

tests:
  planning-graph-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - planning-graph
